[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cloakcraft = "DsCP619hPxpvY1SKfCqoKMB7om52UJBKBewevvoNN7Ha"

[programs.devnet]
cloakcraft = "DsCP619hPxpvY1SKfCqoKMB7om52UJBKBewevvoNN7Ha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=88ac54a3-8850-4686-a521-70d116779182"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "./scripts/build-circuits.sh && anchor build"
