# Compute derived values for transfer circuit
spending_key = "0x000000000000000000000000000000000000000000000000000000000000007b"
token_mint = "0x032e0f3b8f8b472d79a3109229a727e71159eefa393e064bafacf7c4575f14dd"
in_amount = "0x00000000000000000000000000000000000000000000000000000000000001f4"
in_randomness = "0x000000000000000000000000000000000000000000000000000000000000006f"
out_pub_x_1 = "0x0000000000000000000000000000000000000000000000000000000000003039"
out_amount_1 = "0x000000000000000000000000000000000000000000000000000000000000012c"
out_randomness_1 = "0x00000000000000000000000000000000000000000000000000000000000000de"
out_pub_x_2 = "0x0000000000000000000000000000000000000000000000000000000000010932"
out_amount_2 = "0x00000000000000000000000000000000000000000000000000000000000000c8"
out_randomness_2 = "0x000000000000000000000000000000000000000000000000000000000000014d"
