# Test values from note5
# spending_key: 04a694170f21d23b90e6ad76c0ba9ac1af15dd932cac919a8fa072b17f82e876
# commitment: 0c89fc43faea372bc81c543997b9ea90aff30643a7180e4b88dc6b6e946035c0
# leaf_index: 5

spending_key = "2103570087217973318626898423278564870291177499756325428880822044450929961078"
commitment = "5671553303694076824957196685359696250583136224595448332265088876516827215296"
leaf_index = "5"
